@startuml
class Character.Nerd {
}
class Screen.HowToPlay.HowToPlayScreen {
- VBox createSection(String,String,String)
}

class Screen.TitleScreen {
- ScreenManager begin
- Text title
- Button start
- Button how_to_play
- Button exit
}

class Logic.GameSession {
- {static} Player player
- {static} int MAX_ROUNDS
- {static} int round
- {static} int initialStamina
+ {static} void setPlayer(Player)
+ {static} Player getPlayer()
+ {static} int getRound()
+ {static} int getMaxRounds()
+ {static} int getInitialStamina()
+ {static} void advanceRound()
+ {static} boolean isLastRound()
}


enum Character.CharacterType {
+  HUSTLER
+  GENIUS
+  ATHLETE
+  SOCIALITE
}

class Screen.Choosing.init {
- String des
- String name_button
- Text descirption
- String picture
- Circle circle
- ImageView imageView
- Button Player_button
+ void addAll()
+ Button getPlayer_button()
+ void setPlayer(Button)
+ String getName_button()
+ void setName_button(String)
+ String getDes()
+ void setDes(String)
+ String getPicture()
+ void setPicture(String)
}


class Screen.Choosing.ChoosingScreen {
- String[] avatarPaths
- String[] archetypeNames
- String[] prosCons
- int selectedIndex
- Label selectedTitle
- Label selectedDesc
- void refreshDescription()
- String cardStyle(boolean)
- ImageView safeAvatar(String)
}


class Screen.Game.ActionButtoninit {
- GamePane gamePane
}

class Main.main {
+ void start(Stage)
+ {static} void main(String[])
}

class Item.BaseItem {
}
abstract class Character.BasePlayer {
- int stamina
- int money
- int education
- int health
- double moneyDiscount
- double educationMultiply
- int healthDecrease
- int staminaDecrease
+ void walk()
+ void study(int)
+ void buyItem(int)
+ int getStamina()
+ void setStamina(int)
+ int getStaminaDecrease()
+ void setStaminaDecrease(int)
+ int getMoney()
+ void setMoney(int)
+ double getMoneyDiscount()
+ void setMoneyDiscount(double)
+ int getEducation()
+ void setEducation(int)
+ double getEducationMultiply()
+ void setEducationMultiply(double)
+ int getHealth()
+ void setHealth(int)
+ int getHealthDecrease()
+ void setHealthDecrease(int)
}


class Screen.Game.Gamebar {
- Button go_back
- Button end_round
- Button action
- Label roundLabel
+ void updateRound(int,int)
+ Button getGo_back()
+ Button getEnd_round()
+ Button getAction()
+ void setActionVisible(boolean)
+ void setOnActionClick(Runnable)
}


class Character.Player {
- CharacterType type
- String imagePath
+ CharacterType getType()
+ void setType(CharacterType)
+ String getImagePath()
+ void setImagePath(String)
+ void clampAllStats()
}


class Character.GymBro {
}
class Character.PlayerFactory {
+ {static} Player create(CharacterType)
}

class Character.Otaku {
}
class Character.NormalGuy {
}
class Screen.ScreenManager {
- Stage stage
+ void showTitle()
+ void showChoose()
+ void endGame()
+ void showGame()
+ Stage getStage()
+ void setStage(Stage)
+ void showHowToPlay()
+ void showResult()
}


class Main.main2 {
- int TILE_SIZE
- int[][] map
- int playerRow
- int playerCol
- Rectangle player
- boolean isMoving
+ void start(Stage)
- void drawMap(Pane)
- List<int[]> findPath(int,int,int,int)
- void walkPath(List<int[]>)
+ {static} void main(String[])
}


class Screen.Result.ResultScreen {
- String[] Badge
- HBox createStatusRow(String,int)
- ImageView createBadge(int)
}


class Screen.Game.StatusTab {
- ProgressBar staminaBar
- Label staminaLabel
- VBox createBar(String,String)
+ void updateStatus()
- void animateBar(ProgressBar,double)
}


class Logic.GamePane {
- int TILE_SIZE
- boolean[][] clickable
- Image wallImage
- Image floorImage
- Image gym
- Image imgDown
- Image imgLeft
- Image imgRight
- Image imgUp
- Runnable onReachBuilding
- Runnable onLeaveBuilding
- Runnable onStatusChange
- int[][] map
- int playerRow
- int playerCol
- ImageView player
- boolean isMoving
- void drawMap()
- List<int[]> findPath(int,int,int,int)
- void clickablePath()
- void walkPath(List<int[]>)
+ boolean CheckPlayer()
+ void setOnReachBuilding(Runnable)
+ void setOnLeaveBuilding(Runnable)
+ int getPlayerRow()
+ int getPlayerCol()
+ void setPlayerRow(int)
+ void setPlayerCol(int)
+ void setOnStatusChange(Runnable)
+ void resetPlayerToStart()
+ boolean isPlayerMoving()
}


class Screen.Game.GameScreen {
- void handleEndRound(ScreenManager,Gamebar,GamePane,StatusTab)
}



Character.BasePlayer <|-- Character.Nerd
Screen.HowToPlay.BorderPane <|-- Screen.HowToPlay.HowToPlayScreen
javafx.scene.layout.VBox <|-- Screen.TitleScreen
javafx.scene.layout.VBox <|-- Screen.Choosing.init
javafx.scene.layout.BorderPane <|-- Screen.Choosing.ChoosingScreen
Screen.Game.Gamebar <|-- Screen.Game.ActionButtoninit
javafx.application.Application <|-- Main.main
javafx.scene.layout.BorderPane <|-- Screen.Game.Gamebar
Character.BasePlayer <|-- Character.Player
Character.BasePlayer <|-- Character.GymBro
Character.BasePlayer <|-- Character.Otaku
Character.BasePlayer <|-- Character.NormalGuy
javafx.application.Application <|-- Main.main2
Screen.Result.StackPane <|-- Screen.Result.ResultScreen
Screen.Game.VBox <|-- Screen.Game.StatusTab
javafx.scene.layout.Pane <|-- Logic.GamePane
Screen.Game.VBox <|-- Screen.Game.GameScreen
@enduml